{
  lib,
  config,
  pkgs,
  username,
  constants,
  ...
}:
let
  cfg = config.darwin.apps.jankyborders;
  inherit (constants) colors;

  # Helper to convert hex color to 0x format
  toJankyColor = hex: "0xff${lib.strings.removePrefix "#" hex}";
in
{
  options.darwin.apps.jankyborders = {
    enable = lib.mkEnableOption "Enable JankyBorders window borders";
  };

  config = lib.mkIf cfg.enable {
    # Install JankyBorders via Homebrew
    homebrew.brews = [ "borders" ];

    # Configure JankyBorders through launchd service
    launchd.user.agents.jankyborders = {
      serviceConfig = {
        Label = "com.user.jankyborders";
        ProgramArguments = [
          "/opt/homebrew/bin/borders"
          "active_color=${toJankyColor colors.orange}"
          "inactive_color=${toJankyColor colors.bg2}"
          "width=6.0"
          "style=round"
          "hidpi=on"
        ];
        KeepAlive = true;
        RunAtLoad = true;
        StandardOutPath = "/tmp/jankyborders.log";
        StandardErrorPath = "/tmp/jankyborders.error.log";
      };
    };

    # Alternative configuration via home-manager file
    home-manager.users.${username} = {
      home.file = {
        ".config/borders/bordersrc" = {
          text = ''
            #!/bin/bash

            # JankyBorders configuration
            # Gruvbox Dark theme
            # Generated by Nix

            borders \
              active_color=${toJankyColor colors.orange} \
              inactive_color=${toJankyColor colors.bg2} \
              width=6.0 \
              style=round \
              hidpi=on
          '';
          executable = true;
        };
      };
    };
  };
}
