keys:
  - &rgo_laptop age1rlccamyq78ecmftwh5cu6qwf5zqmv5tysth2w3l948kr4yyxeqnqdymjk3
  - &rgo_desktop age1kh66yknmm78fls7qx8hujmjyprpflq2g44rtrcxd8ln0e4k3m9vqsq8l2h

creation_rules:
  - path_regex: (secrets\.yaml|secrets_plain\.yaml)$
    key_groups:
      - age:
          - *rgo_laptop
          - *rgo_desktop
