keys:
  - &desktop age1kh66yknmm78fls7qx8hujmjyprpflq2g44rtrcxd8ln0e4k3m9vqsq8l2h
  - &laptop age15m575qmh7j6pa2j8x5q0mp2zpn87lsvswhcmlrs4q343lxgpzswsxquvy2

creation_rules:
  - path_regex: (secrets\.yaml|secrets_plain\.yaml)$
    key_groups:
      - age:
          - *desktop
          - *laptop
